---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio
  namespace: gourmetgram-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-studio
  template:
    metadata:
      labels:
        app: label-studio
    spec:
      containers:
        - name:  label-studio
          image: heartexlabs/label-studio:1.16.0
          ports:
            - containerPort: 8080
          env:
            - name: LABEL_STUDIO_URL
              value: "http://label-studio:8080"
            - name: LABEL_STUDIO_USERNAME
              value: "labelstudio@example.com"
            - name: LABEL_STUDIO_PASSWORD
              value: "labelstudio"
            - name: LABEL_STUDIO_USER_TOKEN
              value: "ab9927067c51ff279d340d7321e4890dc2841c4a"
            - name: POSTGRES_HOST
              value: "app-db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "appdb"
#          command: ["/bin/sh", "-c"]
#          args:
#            - |
#              pip install psycopg2-binary boto3 &&
#              mlflow server --backend-store-uri postgresql://user:password@postgres/mlflowdb \
#              --artifacts-destination s3://mlflow-artifacts/ --serve-artifacts --host 0.0.0.0 --port 8000
---
apiVersion: v1
kind: Service
metadata:
  name: label-studio
  namespace: gourmetgram-platform
spec:
  selector:
    app: label-studio
  ports:
    - port: 5000
      targetPort: 8080
  externalIPs:
    - {{ .Values.mlflow.externalIP }}
