version: "3.8"
services:
  inference:
    build: ./inference_service
    ports:
      - "8000:8000"
    volumes:
      - ./tmp_stream:/workspace/tmp_stream
    command: uvicorn app:app --host 0.0.0.0 --port 8000
