FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
WORKDIR /app
COPY deps/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# We mount your code at runtime, so no COPY . . here is strictly necessary
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9090"]