version: '3.8'

services:
  # ────── MinIO for MLflow ──────
  minio-mlflow:
    image: minio/minio
    container_name: minio-mlflow
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "your-access-key"
      MINIO_ROOT_PASSWORD: "your-secret-key"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_mlflow:/data

  mlflow-create-bucket:
    image: minio/mc
    depends_on:
      minio-mlflow:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set mlflow http://minio-mlflow:9000 your-access-key your-secret-key && \
      mc mb mlflow/mlflow-artifacts || echo 'Bucket exists'
      "

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflowdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.2
    container_name: mlflow
    restart: always
    depends_on:
      - minio-mlflow
      - postgres
      - mlflow-create-bucket
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:8000
      MLFLOW_S3_ENDPOINT_URL: http://minio-mlflow:9000
      AWS_ACCESS_KEY_ID: "your-access-key"
      AWS_SECRET_ACCESS_KEY: "your-secret-key"
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "pip install psycopg2-binary boto3 && \
      mlflow server \
        --backend-store-uri postgresql://user:password@postgres/mlflowdb \
        --artifacts-destination s3://mlflow-artifacts/ \
        --serve-artifacts --host 0.0.0.0 --port 8000"
  
  # ────── MinIO for Ray ──────
  minio-ray:
    image: minio/minio
    container_name: minio-ray
    restart: always
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: "your-access-key"
      MINIO_ROOT_PASSWORD: "your-secret-key"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_ray:/data

  ray-create-bucket:
    image: minio/mc
    depends_on:
      minio-ray:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set ray http://minio-ray:9000 your-access-key your-secret-key && \
      mc mb ray/ray || echo 'Bucket exists'
      "

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - minio-ray
      - ray-create-bucket
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ALLOW_EMBEDDING: "true"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  minio_data_mlflow:
  postgres_data:
  minio_data_ray:
  grafana_data:
