FROM rayproject/ray:2.42.1-gpu

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends docker.io && \
    rm -rf /var/lib/apt/lists/*


COPY docker/deps/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt


WORKDIR /app
COPY TrainingScripts/ ./TrainingScripts/