version: '3.8'

services:
  feature_loader:
    image: python:3.9-slim
    container_name: feature_loader
    working_dir: /data
    volumes:
      - features_data:/data
    entrypoint: >
      sh -c "
        apt-get update && \
        apt-get install -y unzip curl && \
        # download from Box (adds ?download=1 for direct file download)
        curl -L -o features_sampled.zip 'https://nyu.box.com/s/av7hp140273hrh1tyl9d1jo28k5lt6mr?download=1' && \
        mkdir -p /data/Features && \
        unzip -qq features_sampled.zip -d /data/Features
      "
    restart: "no"

volumes:
  features_data: