name: "efficientnet_b3_lora_opt"
platform: "onnxruntime_onnx"
max_batch_size: 256

input [
  { name: "mel_input", data_type: TYPE_FP32, dims: [1, 64, 313] }
]

output [
  { name: "effnet_output", data_type: TYPE_FP32, dims: [206] }
]

dynamic_batching {
  preferred_batch_size: [64, 128, 256]
  max_queue_delay_microseconds: 50
}

instance_group [
  { count: 4, kind: KIND_GPU, gpus: [0] }
]
