volumes:
  birdclef-data:
    external: true  # Ensure this volume exists: `docker volume create birdclef-data`

services:
  init-birdclef-data:
    image: python:3.11
    volumes:
      - birdclef-data:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        echo "Installing dependencies..."
        pip install --no-cache-dir gdown

        echo "Creating dataset directory..."
        mkdir -p /data/BirdCLEF-2025 && cd /data/BirdCLEF-2025

        echo "Downloading BirdCLEF dataset from Google Drive..."
        gdown --id 1w7mTNbrdxJ9YbqC10DJRYiD0YG95q97z -O birdclef_dataset.zip

        echo "Extracting dataset..."
        unzip -q birdclef_dataset.zip
        rm birdclef_dataset.zip

        echo "Verifying folder structure..."
        ls -lh /data/BirdCLEF-2025

        echo "Dataset setup complete."
    restart: "no"
