version: "3.8"

volumes:
  birdclef_root: {}

services:
  extract-download:
    container_name: etl_download_birdclef
    image: python:3.11
    user: 1000:1000
    environment:
      - KAGGLE_CONFIG_DIR=/data/kaggle
    volumes:
      - birdclef_root:/data
      - ../kaggle:/data/kaggle:ro
    working_dir: /data
    command: >
      bash -c "
        set -e
        echo '[INFO] Installing Kaggle CLI...'
        pip install --quiet kaggle

        echo '[INFO] Downloading dataset...'
        mkdir -p birdclef-2025 && cd birdclef-2025
        kaggle competitions download -c birdclef-2025
        unzip -qq birdclef-2025.zip && rm birdclef-2025.zip

        echo '[INFO] Contents of /data/birdclef-2025:'
        ls -lh /data/birdclef-2025
      "

  upload-raw:
    container_name: etl_upload_raw
    image: rclone/rclone:latest
    environment:
      - RCLONE_CONTAINER=object-persist-project38
    volumes:
      - birdclef_root:/data
      - ../config/rclone:/root/.config/rclone:ro
    entrypoint: /bin/sh
    command: >
      -c "
        set -e
        echo '[INFO] Uploading to object store: chi_uc:$RCLONE_CONTAINER/raw'

        rclone copy /data/birdclef-2025/train_audio chi_uc:$RCLONE_CONTAINER/raw/train_audio --progress
        rclone copy /data/birdclef-2025/train.csv chi_uc:$RCLONE_CONTAINER/raw/
        rclone copy /data/birdclef-2025/taxonomy.csv chi_uc:$RCLONE_CONTAINER/raw/

        echo '[INFO] Cleaning up local staging...'
        rm -rf /data/birdclef-2025

        echo '[INFO] Upload and cleanup complete!'
      "
