version: "3.8"

volumes:
  birdclef: {}

services:
  extract-data:
    container_name: etl_extract_data
    image: python:3.11
    user: 1000:1000 # Run as non-root user (maps to 'cc')
    volumes:
      - birdclef:/data
      - ../kaggle:/home/cc/.kaggle:ro # Mount kaggle.json securely
    working_dir: /data
    entrypoint: /bin/bash
    command: >
      -c "
        set -e
        echo '[INFO] Setting up virtualenv...'
        python3 -m venv /data/venv
        source /data/venv/bin/activate

        echo '[INFO] Installing Kaggle CLI...'
        pip install --no-cache-dir kaggle --quiet

        export KAGGLE_CONFIG_DIR=/home/cc/MLOps/data_pipeline/kaggle

        echo '[INFO] Downloading dataset...'
        mkdir -p birdclef-2025 && cd birdclef-2025
        kaggle competitions download -c birdclef-2025
        unzip -qq birdclef-2025.zip
        rm birdclef-2025.zip
        ls -lh
      "

  sample-production:
    container_name: etl_sample_prod
    image: python:3.11
    user: 1000:1000
    volumes:
      - birdclef:/data
    working_dir: /data/birdclef-2025
    entrypoint: /bin/bash
    command: >
      -c "
        echo '[INFO] Sampling 30% of train_soundscapes for production simulation...'
        mkdir -p production_sample
        total=\$(ls train_soundscapes/*.ogg | wc -l)
        count=\$((total * 3 / 10))
        ls -1 train_soundscapes/*.ogg | sort | tail -n \$count | while read f; do
            cp \$f production_sample/
        done
        echo '[INFO] Sampled files:'
        ls -lh production_sample | head
      "

  upload-data:
    container_name: etl_upload
    image: rclone/rclone:latest
    user: 1000:1000
    volumes:
      - birdclef:/data
      - ../config/rclone:/root/.config/rclone:ro
    entrypoint: /bin/sh
    command: >
      -c "
        if [ -z \"$RCLONE_CONTAINER\" ]; then
          echo '[ERROR] RCLONE_CONTAINER is not set!'
          exit 1
        fi

        echo '[INFO] Uploading train_audio...'
        rclone copy /data/birdclef-2025/train_audio chi_uc:$RCLONE_CONTAINER/raw/train_audio \
          --transfers=32 --checkers=16 --progress

        echo '[INFO] Uploading metadata...'
        rclone copy /data/birdclef-2025/train.csv chi_uc:$RCLONE_CONTAINER/raw/
        rclone copy /data/birdclef-2025/taxonomy.csv chi_uc:$RCLONE_CONTAINER/raw/

        echo '[INFO] Uploading sampled production data...'
        rclone copy /data/birdclef-2025/production_sample chi_uc:$RCLONE_CONTAINER/raw/production/train_soundscapes_subset \
          --transfers=16 --checkers=8 --progress

        echo '[✅ SUCCESS] Data upload complete.'
      "
