version: "3.9"

volumes:
  etl_volume: {}

services:
  extract-download:
    container_name: etl_download_birdclef
    image: python:3.11
    user: root
    environment:
      - KAGGLE_CONFIG_DIR=/root/.kaggle
    volumes:
      - etl_volume:/workspace/tmp_download
      - ../kaggle:/root/.kaggle:ro
    working_dir: /workspace/tmp_download
    command: >
      bash -c "
        set -e
        echo '[INFO] Installing Kaggle CLI...'
        pip install kaggle --quiet

        echo '[INFO] Downloading BirdCLEF 2025 dataset...'
        mkdir -p birdclef-2025 && cd birdclef-2025
        kaggle competitions download -c birdclef-2025
        unzip -qq birdclef-2025.zip
        rm birdclef-2025.zip

        echo '[INFO] Listing extracted files:'
        ls -lh /workspace/tmp_download/birdclef-2025
      "

  upload-raw:
    container_name: etl_upload_raw
    image: rclone/rclone:latest
    environment:
      - RCLONE_CONTAINER=object-persist-project38
    volumes:
      - etl_volume:/workspace/tmp_download
      - ~/.config/rclone:/config/rclone:ro
    entrypoint: /bin/sh
    command: >
      -c "
        echo '[INFO] Listing extracted files:'
        ls -lh /workspace/tmp_download/birdclef-2025
        set -e
        echo '[INFO] Uploading to object store: chi_uc:$RCLONE_CONTAINER/raw'

        rclone copy /workspace/tmp_download/birdclef-2025/train_audio chi_uc:$RCLONE_CONTAINER/raw/train_audio --progress
        rclone copy /workspace/tmp_download/birdclef-2025/train.csv chi_uc:$RCLONE_CONTAINER/raw/
        rclone copy /workspace/tmp_download/birdclef-2025/taxonomy.csv chi_uc:$RCLONE_CONTAINER/raw/

        echo '[INFO] Upload complete!'
      "
