version: "3.8"

volumes:
  birdclef_volume: {}

services:
  extract-download:
    container_name: etl_download_birdclef
    image: python:3.11
    user: 1000:1000
    environment:
      - KAGGLE_CONFIG_DIR=/workspace/kaggle
    volumes:
      - birdclef_volume:/workspace
      - ../kaggle:/workspace/kaggle:ro
    working_dir: /workspace
    command: >
      bash -c "
        set -e
        echo '[INFO] Creating download directory...'
        mkdir -p workspace_data && cd workspace_data

        echo '[INFO] Creating virtualenv...'
        python -m venv /tmp/venv && source /tmp/venv/bin/activate

        echo '[INFO] Installing Kaggle CLI...'
        pip install --no-cache-dir kaggle

        echo '[INFO] Downloading BirdCLEF dataset...'
        kaggle competitions download -c birdclef-2025
        unzip -qq birdclef-2025.zip && rm birdclef-2025.zip

        echo '[INFO] Final contents:'
        ls -lh /workspace/workspace_data
      "

  upload-raw:
    container_name: etl_upload_raw
    image: rclone/rclone:latest
    environment:
      - RCLONE_CONTAINER=object-persist-project38
    volumes:
      - birdclef_volume:/workspace
      - ../config/rclone:/root/.config/rclone:ro
    entrypoint: /bin/sh
    command: >
      -c "
        set -e
        echo '[INFO] Uploading raw data from workspace_data to object store...'
        rclone copy /workspace/workspace_data/train_audio chi_uc:$RCLONE_CONTAINER/raw/train_audio --progress
        rclone copy /workspace/workspace_data/train.csv chi_uc:$RCLONE_CONTAINER/raw/
        rclone copy /workspace/workspace_data/taxonomy.csv chi_uc:$RCLONE_CONTAINER/raw/
        echo '[INFO] Upload complete.'
        rm -rf /workspace/workspace_data
      "
