global:
  scrape_interval: 5s  # How often to scrape targets by default

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi_server:8000"]

  - job_name: "triton"
    metrics_path: /metrics
    static_configs:
      - targets: ["triton_server:8002"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
