version: "3.8"

volumes:
  birdclef_data:
    external: true

services:
  init-data:
    image: python:3.11
    volumes:
      - birdclef_data:/data
    working_dir: /data
    command:
      - bash
      - -c
      - |
        set -e
        echo "Creating BirdCLEF data directory..."
        mkdir -p /data/BirdCLEF && cd /data/BirdCLEF

        echo "Downloading dataset..."
        curl -L https://drive.google.com/file/d/1NiRW10HCZKg_AqGjbm-mlHO5FA1XskmW/view?usp=sharing --output birdclef_dataset.zip

        echo "Extracting..."
        unzip -q birdclef_dataset.zip
        rm birdclef_dataset.zip

        echo "BirdCLEF dataset is ready at /data/BirdCLEF/features_sampled/"
    restart: "no"
