name: "embedding_classifier_opt"
platform: "onnxruntime_onnx"
max_batch_size: 512

input [
  { name: "embedding_input", data_type: TYPE_FP32, dims: [2048] }
]

output [
  { name: "embedding_output", data_type: TYPE_FP32, dims: [206] }
]

dynamic_batching {
  preferred_batch_size: [128, 256, 512]
  max_queue_delay_microseconds: 50
}

instance_group [
  { count: 4, kind: KIND_GPU, gpus: [0] }
]
